site_name: Programming with Python
site_url: https://programming-with-python.netlify.app
nav:
  - Home: index.md
  - Course:
      - Chapter 1 - Basic Concepts: course/chapter1.md
      - Chapter 2 - Collection Types: course/chapter2.md
      - Chapter 3 - Control Flow Statements: course/chapter3.md
      - Chapter 4 - Functions and Modules: course/chapter4.md
      - Chapter 5 - tkinter and Peek of OOP: course/chapter5.md
      - Chapter 6 - Building a Simple Desktop Youtube Downloader: course/chapter6.md
      - Activity 1 - Coding Activity: course/activity1.md
  - About: about.md
plugins:
  - search
  - timetoread:
      allPages: True
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences
extra_css:
  - css/custom.css
theme:
  name: material
  custom_dir: overrides/
