site_name: Programming with Python
site_url: https://programming-with-python.netlify.app
nav:
  - Home: index.md
  - About: about.md
plugins:
  - search
  - timetoread:
      allPages: True
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences
extra_css:
  - css/custom.css
